language: r
sudo: false
cache: packages
cran: https://cloud.r-project.org

r_packages:
  - rmarkdown

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
